import { Inter } from "next/font/google";
import "./globals.css";
import { pdfjs } from "react-pdf";
const inter = Inter({ subsets: ["latin"] });
// configure Pdf
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  "pdfjs-dist/build/pdf.worker.min.js",
  import.meta.url
).toString();
// end of configure Pdf
export const metadata = {
  title: "elsayad Shipping",
  description: "Generated by tommy Elsayad",
};

export default function RootLayout({ children }) {
  // const storemy = createStore(mystore);

  return (
    <html dir="rtl" lang="en">
      <body>{children}</body>
    </html>
  );
}
